
###
GET http://localhost:3001/api/posts/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJWbGFkaW1pciIsImxhc3RuYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi84LmpwZyIsImlkIjoyLCJpYXQiOjE2NDkxMDE3MTN9.sheM_XL95MwyKfODtSY-MhiyixsUSkpBqUbRwjWHddw

###
GET http://localhost:3001/api/posts/wall/shivangikakkar
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJWbGFkaW1pciIsImxhc3RuYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi84LmpwZyIsImlkIjoyLCJpYXQiOjE2NDkxMDE3MTN9.sheM_XL95MwyKfODtSY-MhiyixsUSkpBqUbRwjWHddw

###
GET http://localhost:3001/api/posts/62599cc09adf8f000123f09a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJWbGFkaW1pciIsImxhc3RuYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi84LmpwZyIsImlkIjoyLCJpYXQiOjE2NDkxMDE3MTN9.sheM_XL95MwyKfODtSY-MhiyixsUSkpBqUbRwjWHddw

###
DELETE  http://localhost:3001/api/posts/62599cc09adf8f000123f09a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJWbGFkaW1pciIsImxhc3RuYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi84LmpwZyIsImlkIjoyLCJpYXQiOjE2NDkxMDE3MTN9.sheM_XL95MwyKfODtSY-MhiyixsUSkpBqUbRwjWHddw

###
POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJWbGFkaW1pciIsImxhc3RuYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi84LmpwZyIsImlkIjoyLCJpYXQiOjE2NDkxMDE3MTN9.sheM_XL95MwyKfODtSY-MhiyixsUSkpBqUbRwjWHddw

    {
        "src": "https://w2.chabad.org/media/images/1187/SvDB11878116.jpg?_i=_n504BC99DD0473598AAE3BCDC5D75568D",
        "caption": "Of Mugs and Family Ties",
        "owner": "newpaltz_benevolent",
        "likes": [],
        "comments": [],
        "isPublic": true
    }


###
PATCH  http://localhost:3001/api/posts/62599cc09adf8f000123f09a
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJWbGFkaW1pciIsImxhc3RuYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi84LmpwZyIsImlkIjoyLCJpYXQiOjE2NDkxMDE3MTN9.sheM_XL95MwyKfODtSY-MhiyixsUSkpBqUbRwjWHddw

{
    "owner": "newpaltz_benevolent"
}

###
POST http://localhost:3001/api/posts/seed
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJWbGFkaW1pciIsImxhc3RuYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi84LmpwZyIsImlkIjoyLCJpYXQiOjE2NDkxMDE3MTN9.sheM_XL95MwyKfODtSY-MhiyixsUSkpBqUbRwjWHddw
