http://localhost:3001

###
GET http://localhost:3001/api/users/
Authorization: bearer {{ login.response.body.data.token }}

###
GET http://localhost:3001/api/users/handle/shivangikakkar
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJWbGFkaW1pciIsImxhc3RuYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi84LmpwZyIsImlkIjoyLCJpYXQiOjE2NDkxMDE3MTN9.sheM_XL95MwyKfODtSY-MhiyixsUSkpBqUbRwjWHddw

###
GET http://localhost:3001/api/users/625db8cf3e8e3af37ae51124

###
DELETE  http://localhost:3001/api/users/625db8cf3e8e3af37ae51124
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJWbGFkaW1pciIsImxhc3RuYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi84LmpwZyIsImlkIjoyLCJpYXQiOjE2NDkxMDE3MTN9.sheM_XL95MwyKfODtSY-MhiyixsUSkpBqUbRwjWHddw


###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "firstname": "Shivi",
    "lastname": "hey",
    "handle": "shiv",
    "password": "cof",
    "email": "shiv@gmail.com",
    "pic": "https://randomuser.me/api/portraits/women/21.jpg"
}

###
PATCH  http://localhost:3001/api/users/625db8cf3e8e3af37ae51124
Content-Type: application/json

{

   
    "password": "coffee"
   
}

###
# @name login
POST  http://localhost:3001/api/users/login
Content-Type: application/json

{

    "email": "shiv@gmail.com",
    "password": "coffeee"
   
}

###
POST  http://localhost:3001/api/users/seed

###
https://api.openweathermap.org/data/2.5/weather?q=London,uk&appid={{$dotenv OPENWEATHER_KEY}}

###
https://api.coinbase.com/v2/exchange-rates

###
https://maps.googleapis.com/maps/api/place/textsearch/json?query=University&key={{$dotenv GOOGLE_API_KEY_1}}